scheduler/app/__init__.py
from flask import Flask
from pymongo import MongoClient
from flask.ext.login import LoginManager
from flask.ext.bower import Bower
from flask.ext.bootstrap import Bootstrap

mongo = MongoClient()
db = mongo.test

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'main.index'

bower = Bower()
bootstrap = Bootstrap()

def create_app():
    # app = Flask('scheduler')
    app = Flask(__name__)

    app.config.from_object('config')

    login_manager.init_app(app)
    bower.init_app(app)
    bootstrap.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .api import api as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix='/api')

    from .glp import glp as glp_blueprint
    app.register_blueprint(glp_blueprint)


    return app

scheduler/app/api/__init__.py
from flask import Flask
from flask.ext.restful import Api

from flask import Blueprint

api = Blueprint('api', __name__)

from . import authentication, course, student, user, admin

scheduler/app/glp/__init__.py
from flask import Blueprint

glp = Blueprint('glp', __name__)

# from ..database import CourseDAO
# from ..database import StudentDAO
# from ..database import FacultyDAO
# from ..database import UserDAO
# from ..database import ConcentrationDAO
#
# from .. import db
#
# #Constants used for database purposes
# studentDao = StudentDAO.StudentDAO(db)
# facultyDao = FacultyDAO.FacultyDAO(db)
# courseDao  = CourseDAO.CourseDAO(db)
# userDao    = UserDAO.UserDAO(db)
# concentrationDao = ConcentrationDAO.ConcentrationDAO(db)
# semesterToUse = 1 ### FOR NOW, HARD CODE OUR SEMESTER I

scheduler/app/main/__init__.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)

from . import views

# @main.route('/')
# def index():
    # return 'go team go'

scheduler/app/main/views.py
from flask import render_template, redirect, request, url_for, flash
from flask.ext.login import login_user, logout_user, login_required
from . import main
from ..model.user import User
from ..model.student import Student
from .auth_form import LoginForm
from ..api import crossDomain
from ..controller import studentController, adminController, userController


@main.route('/', methods=['GET', 'POST'])
@crossDomain.crossdomain('*')
def index():
    form = LoginForm()
    if form.validate_on_submit():
        if User.is_user(form.username.data):
            user = User(form.username.data)
            print user
            if user is not None and user.verify_password(form.password.data):
                login_user(user, form.remember_me.data)

                if user.is_admin(form.username.data) or user.is_developer(form.username.data):
                    return redirect(request.args.get('next') or url_for('.adminInfo', username=form.username.data))
                else:
                    return redirect(request.args.get('next') or url_for('.studentInfo', username=form.username.data))

        flash('Invalid username or password.')
    return render_template('login.html', form=form, authData=None)


@main.route('/logout')
@login_required
@crossDomain.crossdomain('*')
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('main.index'))

########## User Pages ##########


@main.route('/user/<username>')
@login_required
def studentInfo(username):
    return render_template('/student/index.html',
                           authData=userController.get_auth_data(username),
                           data=studentController.get_student_info(username))


@main.route('/user/<username>/dashboard')
@login_required
def studentDashboard(username):
    return render_template('/student/student_dashboard.html',
                           authData=userController.get_auth_data(username),
                           data=studentController.get_student_info(username))


@main.route('/course_data/<username>')
@login_required
def aggregateCourseData(username):

    return render_template('/admin/aggregate_course_data.html',
                           authData=userController.get_auth_data(username),
                           data=adminController.get_course_aggregate_data())


@main.route('/<username>/student/<student_id>')
@login_required
def individualStudentData(username, student_id):
    data = Student.get_info(student_id)
    return render_template('admin/student_data.html',
                           authData=userController.get_auth_data(username),
                           data=data)


########## Admin Pages ##########

@main.route('/student_list/<username>')
@login_required
def studentList(username):
    data = adminController.get_student_list()

    return render_template('admin/student_list.html',
                           authData=userController.get_auth_data(username),
                           data=data)


@main.route('/scheduler/<username>')
@login_required
def schedulerView(username):
    data = adminController.get_schedule_data()

    return render_template('admin/schedule.html',
                           authData=userController.get_auth_data(username),
                           data=data)


@main.route('/solution_view/<solution_id>')
@login_required
def solutionView(solution_id):
    pass


@main.route('/new_schedule')
@login_required
def newSchedule():
    pass


@main.route('/new_solution')
@login_required
def newSolution():
    pass


@main.route('/admin_info/<username>')
@login_required
def adminInfo(username):
    data = adminController.get_questions_list()
    return render_template('admin/admin_dashboard.html',
                           authData=userController.get_auth_data(username),
                           data=data)

scheduler/app/model/__init__.py
#KJN Stuff
#Constant pointing to the database. DO NOT CHANGE.
#KJN -- DISCUSS WITH OTHERS GOING FORWARD
from ..database import CourseDAO
from ..database import StudentDAO
from ..database import UserDAO
from ..database import SemesterDAO
from ..database import QuestionDAO
from ..database import FacultyDAO
from ..database import ConcentrationDAO
from ..database import RecommendationDAO
from .. import db

#Constants used for database purposes
studentDao  = StudentDAO.StudentDAO(db)
facultyDao  = FacultyDAO.FacultyDAO(db)
courseDao   = CourseDAO.CourseDAO(db)
userDao     = UserDAO.UserDAO(db)
semesterDao = SemesterDAO.SemesterDAO(db)
questionDao = QuestionDAO.QuestionDAO(db)
concentrationDao = ConcentrationDAO.ConcentrationDAO(db)
recommendationDao = RecommendationDAO.RecommendationDAO(db)

semesterToUse = 1 ### FOR NOW, HARD CODE OUR SEMESTER I

scheduler/app/templates/login.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "template.html" %}
{% block title %}Login{% endblock %}
{% block head %}
  {{ super() }}
    <link href="{{ url_for('static', filename='styles/login.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}

<div class="login-image">
    <img src="{{ url_for('static', filename='images/techBee.png') }}" class="img-responsive pull-left">
</div>

<div class="col-md-4 col-md-offset-1 login-border">
    <div class="page-header">
        <h1>Login</h1>
    </div>
    {{ wtf.quick_form(form) }}
</div>
    {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
        {{ message }}
    </div>
    {% endfor %}
{% endblock %}

scheduler/app/templates/student/index.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "template.html" %}
{% block title %}Student Information{% endblock %}
{% block head %}
    {{ super() }}
    <script src="{{ url_for('static', filename='scripts/studentInfo.js') }}"></script>
    <link href="{{ url_for('static', filename='styles/student.css') }}" rel="stylesheet">

    <script type="text/javascript">
        //Set student data
        var semester = '{{ data.semester }}';
        var username = '{{ authData.name}}';
    </script>
{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div id="studentInfo" class="student-info">
        <div class="student_info">
          <img src="{{ url_for('static', filename='images/Bomberman.gif') }}" class="img-responsive pull-left">
        </div>
        <div class="student_info">
          <span class="info_black">{{data.student_info.firstname}} {{data.student_info.lastname}}</span>
          <span class="glyphicon glyphicon-camera pull-right"></span>
        </div>
        <div class="student_info">
          <span class="info_black" id="specialization">{{data.specialization}}</span><br>
          <span class="grey_text">Specialization</span>
          <span class="glyphicon glyphicon-pencil pull-right"></span>
        </div>
        <div class="student_info">
          <span class="info_black">{{data.student_info.graduation}}</span> <br>
          <span class="grey_text">Target Graduation Date</span>
          <span class="glyphicon glyphicon-pencil pull-right"></span>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div id="completedCourses">
        <table class="table">
          <thead>
            <th>
              <span>Completed Courses</span>
            </th>
          </thead>
          <tbody>
            {% for row in data.completed_courses %}
                <tr>
                  <td>{{ row.coursename }}</td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

      <div id="coursePreferences">
        <table class="table" id="preferencesTable">
          <thead>
            <th>
              <span>Fall 2016 Course Preferences</span>
              <span id="addPreference" class="glyphicon glyphicon-plus-sign pull-right"></span>
            </th>
          </thead>
          <tbody>
            {% for row in data.course_preferences %}
                <tr id="{{row.courseid}}" class="preference-table-row">
                  <td>
                    {{ row.coursename }}
                    <span class="pull-right">
                      <span class="glyphicon glyphicon-arrow-up icon_padding"></span>
                      <span class="glyphicon glyphicon-arrow-down icon_padding"></span>
                      <span class="glyphicon glyphicon-remove icon_padding></span>
                      <span class="glyphicon glyphicon-remove icon_padding></span>
                    </span>
                  </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

      <div id="solutions">
        <table class="table">
          <thead>
            <th>
              <span>Solutions</span>
            </th>
          </thead>
          <tbody>
            {% for row in data.solutions %}
                <tr>
                  <td>
                    {{ row.coursename }}
                    <span class="glyphicon glyphicon-stats pull-right"></span>
                  </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

      <div id="whatIf">
        <table class="table" id="questionsTable">
          <thead>
            <th>
              <span>Questions</span>
            </th>
            <th>
                <span>Answers</span>
                <span id="addQuestion" class="glyphicon glyphicon-plus-sign pull-right"></span>
            </th>
          </thead>
          <tbody>
            {% for row in data.questions %}
                <tr>
                  <td>
                    {{ row.question }}
                  </td>
                  <td>
                        {{ row.answer }}
                  </td>
                    <!--<span class="glyphicon glyphicon-ok pull-right"></span>-->
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- Questions Modal -->
<div class="modal fade" id="questionsModal" role="dialog" style="display: none">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Ask Question</h4>
            </div>
            <div class="modal-body">
            <p>Enter your question for administrators.</p>
                <textarea id="questionTextArea" rows="4" cols="50"></textarea>
            </div>
            <div class="modal-footer">
                <button id="questionBtn" type="button" class="btn btn-default left" data-dismiss="modal">Ask Question</button>
            </div>
        </div>
    </div>
</div>


<!-- Courses Modal -->
<div class="modal fade" id="coursesModal" role="dialog" style="display: none">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add Course</h4>
            </div>
            <div class="modal-body">
            <p>Select Course</p>
                <select id="courseAddSelect">
                  {% for row in data.courses %}
                      <option value="{{row.courseid}}">{{row.coursename}}</option>
                  {% endfor %}
                </select>
            </div>
            <div class="add-course-error"></div>
            <div class="modal-footer">
                <button type="button" id="courseBtn" class="btn btn-default left">Add Course</button>
            </div>
        </div>
    </div>
</div>


{% endblock %}

scheduler/app/templates/student/student_dashboard.html
{% extends "template.html" %}
{% block title %}Student Information - {{  user.id }}{% endblock %}
{% block head %}
  {{ super() }}
    <link href="{{ url_for('static', filename='styles/login.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}

    <p>{{ user.id }}</p>
    <p>Specialization: {{ data.student_info['concentration'] }}</p>
    <p>Credits Earned: {{ data.student_info['credits earned'] }}</p>
    <p>GPA: {{ data.student_info['gpa'] }}</p>
    <p>Expected Graduation: {{ data.student_info['graduation'] }}</p>
    <p>Completed Courses:
        <ul>
        {% for course in data.completed_courses %}
            <li>{{ course }}</li>
        {% endfor %}
        </ul>
    <p>Requested Courses:
        <ul>
        {% for course in data.course_preferences %}
            <li>{{ course }}</li>
        {% endfor %}
        </ul>
{% endblock %}

scheduler/app/templates/template.html
<!doctype html>
<html>
  <head>
    {% block head %}
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="{{ url_for('static', filename='styles/template.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('bower.static', filename='bootstrap/dist/css/bootstrap.min.css') }}" >
 	<link href="{{ url_for('bower.static', filename='bootstrap-modal/css/bootstrap-modal.css') }}" rel="stylesheet" />

    <script src="{{ url_for('bower.static', filename='jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('bower.static', filename='bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('bower.static', filename='bootstrap-modal/js/bootstrap-modalmanager.js') }}"></script>
    <script src="{{ url_for('bower.static', filename='bootstrap-modal/js/bootstrap-modal.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/template.js') }}"></script>
    <title>{% block title %}{% endblock %} - OMSCS Scheduler</title>

    <script type="text/javascript">
        $(document).ready(function() {
            var username = '{{authData.name}}';

            var url = window.location.href;
            if (url.indexOf('student_list') != -1) {
                $('#students').addClass('active');
            } else if (url.indexOf('user') != -1) {
                $('#student_info').addClass('active');
            } else if (url.indexOf('course_data') != -1) {
                $('#course_aggregate_data').addClass('active');
            } else if (url.indexOf('admin_info') != -1) {
                $('#admin_info').addClass('active');
            } else if (url.indexOf('scheduler') != -1) {
                $('#scheduler').addClass('active');
            }

            docready();
        });
    </script>
    {% endblock %}
  </head>
  <body>
    <header class="header">
        {% block header %}
        <div class="page-header navbar-inverse template-header">
            <div class="inline">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <ul class="nav navbar-nav">
                            {% if authData.isStudent or authData.isDeveloper %}
                                <li id="student_info"><a href="{{ url_for('main.studentInfo', username=authData.name) }}">Student Information</a></li>
                                <li id="scheduler"><a href="{{ url_for('main.logout', username=authData.name) }}">Logout</a></li>
                            {% endif %}
                            {% if authData.isAdmin or authData.isDeveloper %}
                                <li id="admin_info"><a href="{{ url_for('main.adminInfo', username=authData.name) }}">Administrator Information</a></li>
                                <li id="course_aggregate_data"><a href="{{ url_for('main.aggregateCourseData', username=authData.name) }}">Course Aggregate Data</a></li>
                                <li id="students"><a href="{{ url_for('main.studentList', username=authData.name) }}">Students</a></li>
                                <li id="scheduler"><a href="{{ url_for('main.schedulerView', username=authData.name) }}">Scheduler</a></li>
                                <li id="scheduler"><a href="{{ url_for('main.logout', username=authData.name) }}">Logout</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </nav>
                <h1 class="header-text text-center">OMSCS Scheduler</h1>
                <img src="{{ url_for('static', filename='images/gt.short.white.png') }}" class="img-responsive pull-right logo">
            </div>
        </div>
        {% endblock %}
    </header>
    <div class="wrap">
        <div class="main" class="container clear-top">
            <div class="content">{% block content %}{% endblock %}</div>
        </div>
    </div>
    <footer class="footer">
      {% block footer %}
        <div class="container">
        </div>
      {% endblock %}
    </footer>
  </body>
</html>